# ========= DQN 超参数 =========
dqn:
  lr: 0.001               # 学习率
  gamma: 0.99             # 折扣因子
  eps_start: 1.0          # 初始探索概率
  eps_end: 0.05           # 最小探索概率
  eps_decay: 0.995        # 衰减速率
  buffer: 10000           # 经验回放容量
  batch: 64               # 每次采样大小
  target_update: 100      # 目标网络更新频率
  episodes: 25            # 每个场景的训练回合数
